"""users table

Revision ID: 6891be48cf34
Revises: 
Create Date: 2020-05-20 21:29:05.667515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6891be48cf34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discription', sa.String(length=1000), nullable=True),
    sa.Column('creation_date', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Float(), nullable=True),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_deadline'), 'order', ['deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_deadline'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
