"""empty message

Revision ID: d559b2977a2b
Revises: 1f196df985d9
Create Date: 2020-06-09 20:16:15.902785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd559b2977a2b'
down_revision = '1f196df985d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rating')
    op.drop_column('order', 'weight')
    op.drop_column('order', 'price')
    # ### end Alembic commands ###
